### PR TITLE
Implement a full slice of database

### PR DESCRIPTION
**Pull request by hulthe**
Implements:
- `CREATE TYPE VARIANT`
- `CREATE TABLE`
- `INSERT INTO`*
  *only supports Value-expressions for now.

Barring ~some~ a lot of refactoring, optimization, and cleaning up the output formatting, the features listed above _should_ be functioning.

### CODE REVIEW

**Comment by hulthe** [comment]
I think this is mergeable now

**Comment by feffes** [comment]
> I think this is mergeable now

failing ci?

**Comment by hulthe** [comment]
@feffes shhh...

**Comment by Baloo1** [comment]
Looks good!

**Review by feffes — CHANGES_REQUESTED** [review]
There are still some problems, investigating further.

**Review by feffes — APPROVED** [review]

**Pull request merged**
