### PR TITLE
Add global resource manager

### PR DESCRIPTION
**Pull request by hulthe**
This is a first draft of a global resource manager, intended to manage concurrent read/write access to all tables in the database.

### CODE REVIEW

**Comment by hulthe** [comment]
the api could probably use some work

**Comment by hulthe** [comment]
hm... now that i think about it, this solution might not work when deleting tables...
EDIT: Nah, it's probably fine.

**Review by feffes — APPROVED** [review]
yes

**Review by ejohnsson6 — APPROVED** [review]
Looking goood!

**Pull request merged**
